// This file is auto-generated by @hey-api/openapi-ts

/**
 * ARQTrace
 * Structured reasoning trace from the VLM Signature.
 *
 * Persisted verbatim to `refinement_run.arq_trace` so prompt-version
 * drift can be diffed in audit UI.
 *
 * All three reasoning fields normalise to `str`. Some VLMs (Gemma in
 * particular) return dict-shaped output for fields whose description
 * sounds list-like — we coerce those to JSON strings so the storage
 * contract stays single-typed without losing the structure.
 */
export type ArqTrace = {
    /**
     * Visual Audit
     * Free-form description of what the VLM sees on the page, no reference to the OCR scaffold.
     */
    visual_audit: string;
    /**
     * Scaffold Match
     * Per-field grounding: which visual region matches each field key, and whether the OCR scaffold has a fragment in that region.
     */
    scaffold_match: string;
    /**
     * Discrepancies
     * OCR errors enumerated: missing fields, mislabels, stale bboxes, artifacts. Each item quotes evidence from the image.
     */
    discrepancies: string;
};

/**
 * BBox
 * 4-point axis-aligned bbox in PDF point space (TOPLEFT origin).
 *
 * We standardise on PDF points + TOPLEFT here because every other
 * layer in the pipeline (Docling, our converter, the frontend) does
 * the same. The Docling source data is BOTTOMLEFT; conversion happens
 * once at ingest, not at refinement time.
 */
export type BBox = {
    /**
     * L
     * Left edge in PDF points
     */
    l: number;
    /**
     * T
     * Top edge in PDF points (TOPLEFT origin)
     */
    t: number;
    /**
     * R
     * Right edge in PDF points
     */
    r: number;
    /**
     * B
     * Bottom edge in PDF points
     */
    b: number;
};

/**
 * BBoxPatch
 * A single edit operation against a DoclingDocument scaffold.
 *
 * Operations
 * ----------
 * - `assign`  — bind an existing fragment to a field key. No geometry change.
 * - `add`     — introduce a new fragment with a fresh bbox + text.
 * Used when OCR missed a region (handwriting, stamps).
 * - `reject`  — flag an existing fragment as artifact. The fragment
 * is kept on the scaffold for audit but excluded from
 * the rendered text layer + field assignments.
 * - `move`    — replace the bbox of an existing fragment. Used to
 * fix off-by-N OCR cropping on noisy regions.
 *
 * All operations carry `reason` (free-form, ARQ-grounded) and
 * `confidence` ∈ [0,1] so downstream code can drop low-confidence
 * edits or surface them for human review.
 */
export type BBoxPatch = {
    /**
     * Op
     * Operation type
     */
    op: 'assign' | 'add' | 'reject' | 'move';
    /**
     * Fragment Id
     * Target fragment for assign/reject/move. Required for those ops.
     */
    fragment_id?: string | null;
    /**
     * Field Key
     * Target field key for assign/add. Uses dot/bracket paths (issuer.name, items[0].quantity).
     */
    field_key?: string | null;
    /**
     * New bbox for add/move in PDF point space (TOPLEFT). Either populate this directly OR populate `box_2d` and let the applier convert. `box_2d` takes precedence when both are set.
     */
    new_bbox?: BBox | null;
    /**
     * Box 2D
     * Gemma-style bbox in 1000x1000 normalized image space (TOPLEFT origin), [x_min, y_min, x_max, y_max]. Converted to PDF points by the applier. Use this directly from VLM output instead of pre-converting on the model side.
     */
    box_2d?: Array<number> | null;
    /**
     * New Text
     * Transcribed text for add. Required for add op.
     */
    new_text?: string | null;
    /**
     * Reason
     * Human-readable justification grounded in visual evidence.
     */
    reason: string;
    /**
     * Confidence
     * Self-reported confidence; downstream may filter on this.
     */
    confidence: number;
};

/**
 * BearerResponse
 */
export type BearerResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * BlockOverlay
 * One Chandra block, projected to render-image pixel coords.
 *
 * `quad` is a 4-point polygon in the same coord system as the page
 * PNG returned by `/pages/{n}.png` — the FE can position absolutely
 * over the image without any further scaling.
 */
export type BlockOverlay = {
    /**
     * Block Id
     */
    block_id: string;
    /**
     * Block Type
     */
    block_type: string;
    /**
     * Text
     */
    text: string;
    /**
     * Quad
     */
    quad: Array<Array<number>>;
    /**
     * Bbox
     */
    bbox: Array<number>;
};

/**
 * Body_auth-reset:forgot_password
 */
export type BodyAuthResetForgotPassword = {
    /**
     * Email
     */
    email: string;
};

/**
 * Body_auth-reset:reset_password
 */
export type BodyAuthResetResetPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * Password
     */
    password: string;
};

/**
 * Body_auth-verify:request-token
 */
export type BodyAuthVerifyRequestToken = {
    /**
     * Email
     */
    email: string;
};

/**
 * Body_auth-verify:verify
 */
export type BodyAuthVerifyVerify = {
    /**
     * Token
     */
    token: string;
};

/**
 * Body_extract-extract_document
 */
export type BodyExtractExtractDocument = {
    /**
     * File
     * PDF or image file
     */
    file: Blob | File;
};

/**
 * Body_extract-extract_document_structured
 */
export type BodyExtractExtractDocumentStructured = {
    /**
     * File
     * PDF or image file
     */
    file: Blob | File;
    /**
     * Doc Type
     * Optional manual override: delivery_order | weighing_bill | invoice | petrol_bill. Leave empty to auto-classify via Gemma vision.
     */
    doc_type?: string | null;
    /**
     * Model
     * LiteLLM model id (gemma-4-31b, gemini-2.5-flash, ...). See GET /extract/models for the full list.
     */
    model?: string;
    /**
     * Dpi
     * PDF render DPI
     */
    dpi?: number;
};

/**
 * DocumentDetail
 */
export type DocumentDetail = {
    document: DocumentSummary;
    /**
     * Page Count
     */
    page_count: number | null;
    /**
     * Pages
     */
    pages: Array<PageDims>;
    current_extraction: ExtractionRunPayload | null;
};

/**
 * DocumentSummary
 */
export type DocumentSummary = {
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Filename
     */
    filename: string;
    /**
     * Mime Type
     */
    mime_type: string;
    /**
     * Size Bytes
     */
    size_bytes: number;
    /**
     * Page Count
     */
    page_count: number | null;
    /**
     * Doc Type
     */
    doc_type: string | null;
    /**
     * Status
     */
    status: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
    /**
     * Detail
     */
    detail: string | {
        [key: string]: string;
    };
};

/**
 * ExtractResponse
 */
export type ExtractResponse = {
    /**
     * Filename
     */
    filename: string;
    /**
     * Page Count
     */
    page_count: number | null;
    /**
     * Markdown
     */
    markdown: string;
    /**
     * Html
     */
    html?: string | null;
    /**
     * Chunks
     */
    chunks?: {
        [key: string]: unknown;
    } | null;
    /**
     * Checkpoint Id
     */
    checkpoint_id?: string | null;
};

/**
 * ExtractionModelOption
 * One row in the FE model dropdown.
 */
export type ExtractionModelOption = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Provider
     */
    provider: string;
    /**
     * Supports Multi Image
     */
    supports_multi_image: boolean;
    /**
     * Is Default
     */
    is_default?: boolean;
    /**
     * Note
     */
    note?: string | null;
};

/**
 * ExtractionRunPayload
 * API-facing slice of an extraction run.
 *
 * The raw `extraction_run.payload` blob (docling_doc + markdown) stays
 * in the database for replay; the API only exposes `extracted_view`
 * (KVPs after overlay). Visual layer is served via separate page-image
 * + OCR-overlay routes.
 */
export type ExtractionRunPayload = {
    /**
     * Extraction Run Id
     */
    extraction_run_id: number;
    /**
     * Doc Type
     */
    doc_type: string;
    /**
     * Schema Version
     */
    schema_version: string;
    /**
     * Llm Model
     */
    llm_model: string;
    /**
     * Duration Ms
     */
    duration_ms: number;
    /**
     * Checkpoint Id
     */
    checkpoint_id: string | null;
    /**
     * Is Current
     */
    is_current: boolean;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Extracted View
     */
    extracted_view: {
        [key: string]: unknown;
    };
    /**
     * Field Pages
     */
    field_pages: {
        [key: string]: number;
    };
    /**
     * Reviews
     */
    reviews: Array<FieldReviewSummary>;
};

/**
 * FieldEdit
 */
export type FieldEdit = {
    /**
     * Field Path
     */
    field_path: string;
    /**
     * Edited Value
     */
    edited_value: unknown;
    /**
     * Remark
     */
    remark?: string | null;
};

/**
 * FieldReviewSummary
 */
export type FieldReviewSummary = {
    /**
     * Field Review Id
     */
    field_review_id: number;
    /**
     * Field Path
     */
    field_path: string;
    /**
     * Edited Value
     */
    edited_value: unknown;
    /**
     * Original Value
     */
    original_value: unknown | null;
    /**
     * Remark
     */
    remark: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * PageBlocksResponse
 */
export type PageBlocksResponse = {
    /**
     * Page No
     */
    page_no: number;
    /**
     * Width Px
     */
    width_px: number;
    /**
     * Height Px
     */
    height_px: number;
    /**
     * Source Width
     */
    source_width: number | null;
    /**
     * Source Height
     */
    source_height: number | null;
    /**
     * Blocks
     */
    blocks: Array<BlockOverlay>;
    /**
     * Field Anchors
     */
    field_anchors: {
        [key: string]: string;
    };
};

/**
 * PageDims
 */
export type PageDims = {
    /**
     * Page No
     */
    page_no: number;
    /**
     * Width Px
     */
    width_px: number;
    /**
     * Height Px
     */
    height_px: number;
};

/**
 * Page[DocumentSummary]
 */
export type PageDocumentSummary = {
    /**
     * Items
     */
    items: Array<DocumentSummary>;
    /**
     * Total
     */
    total?: number | null;
    /**
     * Page
     */
    page: number | null;
    /**
     * Size
     */
    size: number | null;
    /**
     * Pages
     */
    pages?: number | null;
};

/**
 * PatchExtractionRequest
 */
export type PatchExtractionRequest = {
    /**
     * Edits
     */
    edits: Array<FieldEdit>;
};

/**
 * PatchExtractionResponse
 */
export type PatchExtractionResponse = {
    /**
     * Extraction Run Id
     */
    extraction_run_id: number;
    /**
     * Applied
     */
    applied: number;
    /**
     * Extracted View
     */
    extracted_view: {
        [key: string]: unknown;
    };
    /**
     * Reviews
     */
    reviews: Array<FieldReviewSummary>;
};

/**
 * ReextractRequest
 * Body for re-running the LLM pipeline against an already-uploaded doc.
 */
export type ReextractRequest = {
    /**
     * Doc Type
     */
    doc_type?: 'delivery_order' | 'weighing_bill' | 'invoice' | 'petrol_bill' | null;
    /**
     * Model
     */
    model?: string;
    /**
     * Dpi
     */
    dpi?: number;
};

/**
 * RefineResponse
 */
export type RefineResponse = {
    /**
     * Refinement Run Id
     */
    refinement_run_id: number;
    /**
     * Extraction Run Id
     */
    extraction_run_id: number;
    /**
     * Vlm Model
     */
    vlm_model: string;
    /**
     * Prompt Version
     */
    prompt_version: string;
    /**
     * Duration Ms
     */
    duration_ms: number;
    /**
     * Token Usage
     */
    token_usage: {
        [key: string]: unknown;
    } | null;
    result: RefinementResult;
    /**
     * Scaffold Out
     */
    scaffold_out: {
        [key: string]: unknown;
    };
};

/**
 * RefinementResult
 * Full output of one refinement pass — what gets persisted.
 */
export type RefinementResult = {
    arq_trace: ArqTrace;
    /**
     * Patches
     */
    patches: Array<BBoxPatch>;
};

/**
 * StructuredExtractResponse
 * API-facing payload for `/extract/structured`.
 *
 * Intentionally omits `docling_doc` and `markdown` (kept in DB for
 * replay/eval, not surfaced to the UI). `extracted` is the
 * constrained-decoded JSON for the KVP table. The visual layer is
 * served separately via the page-image + OCR-overlay routes.
 */
export type StructuredExtractResponse = {
    /**
     * Document Id
     */
    document_id: string;
    /**
     * Extraction Run Id
     */
    extraction_run_id: number;
    /**
     * Is New Document
     */
    is_new_document: boolean;
    /**
     * Filename
     */
    filename: string;
    /**
     * Doc Type
     */
    doc_type: 'delivery_order' | 'weighing_bill' | 'invoice' | 'petrol_bill';
    /**
     * Model
     */
    model: string;
    /**
     * Page Count
     */
    page_count: number | null;
    /**
     * Duration Ms
     */
    duration_ms: number;
    /**
     * Extracted
     */
    extracted: {
        [key: string]: unknown;
    };
    /**
     * Checkpoint Id
     */
    checkpoint_id?: string | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Password
     */
    password?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * Body_auth-auth:jwt.login
 */
export type Login = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

export type AuthAuthJwtLoginData = {
    body: Login;
    path?: never;
    query?: never;
    url: '/auth/jwt/login';
};

export type AuthAuthJwtLoginErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthAuthJwtLoginError = AuthAuthJwtLoginErrors[keyof AuthAuthJwtLoginErrors];

export type AuthAuthJwtLoginResponses = {
    /**
     * Successful Response
     */
    200: BearerResponse;
};

export type AuthAuthJwtLoginResponse = AuthAuthJwtLoginResponses[keyof AuthAuthJwtLoginResponses];

export type AuthAuthJwtLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/jwt/logout';
};

export type AuthAuthJwtLogoutErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type AuthAuthJwtLogoutResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthRegisterRegisterData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthRegisterRegisterErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthRegisterRegisterError = AuthRegisterRegisterErrors[keyof AuthRegisterRegisterErrors];

export type AuthRegisterRegisterResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type AuthRegisterRegisterResponse = AuthRegisterRegisterResponses[keyof AuthRegisterRegisterResponses];

export type AuthResetForgotPasswordData = {
    body: BodyAuthResetForgotPassword;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type AuthResetForgotPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthResetForgotPasswordError = AuthResetForgotPasswordErrors[keyof AuthResetForgotPasswordErrors];

export type AuthResetForgotPasswordResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type AuthResetResetPasswordData = {
    body: BodyAuthResetResetPassword;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type AuthResetResetPasswordErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthResetResetPasswordError = AuthResetResetPasswordErrors[keyof AuthResetResetPasswordErrors];

export type AuthResetResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type AuthVerifyRequestTokenData = {
    body: BodyAuthVerifyRequestToken;
    path?: never;
    query?: never;
    url: '/auth/request-verify-token';
};

export type AuthVerifyRequestTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthVerifyRequestTokenError = AuthVerifyRequestTokenErrors[keyof AuthVerifyRequestTokenErrors];

export type AuthVerifyRequestTokenResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type AuthVerifyVerifyData = {
    body: BodyAuthVerifyVerify;
    path?: never;
    query?: never;
    url: '/auth/verify';
};

export type AuthVerifyVerifyErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthVerifyVerifyError = AuthVerifyVerifyErrors[keyof AuthVerifyVerifyErrors];

export type AuthVerifyVerifyResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type AuthVerifyVerifyResponse = AuthVerifyVerifyResponses[keyof AuthVerifyVerifyResponses];

export type UsersUsersCurrentUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersUsersCurrentUserErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type UsersUsersCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUsersCurrentUserResponse = UsersUsersCurrentUserResponses[keyof UsersUsersCurrentUserResponses];

export type UsersUsersPatchCurrentUserData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersUsersPatchCurrentUserErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUsersPatchCurrentUserError = UsersUsersPatchCurrentUserErrors[keyof UsersUsersPatchCurrentUserErrors];

export type UsersUsersPatchCurrentUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUsersPatchCurrentUserResponse = UsersUsersPatchCurrentUserResponses[keyof UsersUsersPatchCurrentUserResponses];

export type UsersUsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersUsersDeleteUserErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUsersDeleteUserError = UsersUsersDeleteUserErrors[keyof UsersUsersDeleteUserErrors];

export type UsersUsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsersUsersDeleteUserResponse = UsersUsersDeleteUserResponses[keyof UsersUsersDeleteUserResponses];

export type UsersUsersUserData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersUsersUserErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUsersUserError = UsersUsersUserErrors[keyof UsersUsersUserErrors];

export type UsersUsersUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUsersUserResponse = UsersUsersUserResponses[keyof UsersUsersUserResponses];

export type UsersUsersPatchUserData = {
    body: UserUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersUsersPatchUserErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUsersPatchUserError = UsersUsersPatchUserErrors[keyof UsersUsersPatchUserErrors];

export type UsersUsersPatchUserResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUsersPatchUserResponse = UsersUsersPatchUserResponses[keyof UsersUsersPatchUserResponses];

export type ExtractListExtractionModelsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/extract/models';
};

export type ExtractListExtractionModelsResponses = {
    /**
     * Response Extract-List Extraction Models
     * Successful Response
     */
    200: Array<ExtractionModelOption>;
};

export type ExtractListExtractionModelsResponse = ExtractListExtractionModelsResponses[keyof ExtractListExtractionModelsResponses];

export type ExtractExtractDocumentData = {
    body: BodyExtractExtractDocument;
    path?: never;
    query?: never;
    url: '/extract';
};

export type ExtractExtractDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExtractExtractDocumentError = ExtractExtractDocumentErrors[keyof ExtractExtractDocumentErrors];

export type ExtractExtractDocumentResponses = {
    /**
     * Successful Response
     */
    200: ExtractResponse;
};

export type ExtractExtractDocumentResponse = ExtractExtractDocumentResponses[keyof ExtractExtractDocumentResponses];

export type ExtractExtractDocumentStructuredData = {
    body: BodyExtractExtractDocumentStructured;
    path?: never;
    query?: never;
    url: '/extract/structured';
};

export type ExtractExtractDocumentStructuredErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExtractExtractDocumentStructuredError = ExtractExtractDocumentStructuredErrors[keyof ExtractExtractDocumentStructuredErrors];

export type ExtractExtractDocumentStructuredResponses = {
    /**
     * Successful Response
     */
    200: StructuredExtractResponse;
};

export type ExtractExtractDocumentStructuredResponse = ExtractExtractDocumentStructuredResponses[keyof ExtractExtractDocumentStructuredResponses];

export type ExtractReextractDocumentData = {
    body: ReextractRequest;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}/reextract';
};

export type ExtractReextractDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExtractReextractDocumentError = ExtractReextractDocumentErrors[keyof ExtractReextractDocumentErrors];

export type ExtractReextractDocumentResponses = {
    /**
     * Successful Response
     */
    200: StructuredExtractResponse;
};

export type ExtractReextractDocumentResponse = ExtractReextractDocumentResponses[keyof ExtractReextractDocumentResponses];

export type DocumentsListDocumentsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         * Page number
         */
        page?: number;
        /**
         * Size
         * Page size
         */
        size?: number;
    };
    url: '/documents';
};

export type DocumentsListDocumentsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsListDocumentsError = DocumentsListDocumentsErrors[keyof DocumentsListDocumentsErrors];

export type DocumentsListDocumentsResponses = {
    /**
     * Successful Response
     */
    200: PageDocumentSummary;
};

export type DocumentsListDocumentsResponse = DocumentsListDocumentsResponses[keyof DocumentsListDocumentsResponses];

export type DocumentsDeleteDocumentData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}';
};

export type DocumentsDeleteDocumentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsDeleteDocumentError = DocumentsDeleteDocumentErrors[keyof DocumentsDeleteDocumentErrors];

export type DocumentsDeleteDocumentResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DocumentsDeleteDocumentResponse = DocumentsDeleteDocumentResponses[keyof DocumentsDeleteDocumentResponses];

export type DocumentsGetDocumentDetailData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}';
};

export type DocumentsGetDocumentDetailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsGetDocumentDetailError = DocumentsGetDocumentDetailErrors[keyof DocumentsGetDocumentDetailErrors];

export type DocumentsGetDocumentDetailResponses = {
    /**
     * Successful Response
     */
    200: DocumentDetail;
};

export type DocumentsGetDocumentDetailResponse = DocumentsGetDocumentDetailResponses[keyof DocumentsGetDocumentDetailResponses];

export type DocumentsPatchExtractionData = {
    body: PatchExtractionRequest;
    path: {
        /**
         * Document Id
         */
        document_id: string;
    };
    query?: never;
    url: '/documents/{document_id}/extraction';
};

export type DocumentsPatchExtractionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsPatchExtractionError = DocumentsPatchExtractionErrors[keyof DocumentsPatchExtractionErrors];

export type DocumentsPatchExtractionResponses = {
    /**
     * Successful Response
     */
    200: PatchExtractionResponse;
};

export type DocumentsPatchExtractionResponse = DocumentsPatchExtractionResponses[keyof DocumentsPatchExtractionResponses];

export type DocumentsGetDocumentPagePngData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
        /**
         * Page No
         */
        page_no: number;
    };
    query?: never;
    url: '/documents/{document_id}/pages/{page_no}.png';
};

export type DocumentsGetDocumentPagePngErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsGetDocumentPagePngError = DocumentsGetDocumentPagePngErrors[keyof DocumentsGetDocumentPagePngErrors];

export type DocumentsGetDocumentPagePngResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DocumentsGetDocumentPageBlocksData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
        /**
         * Page No
         */
        page_no: number;
    };
    query?: never;
    url: '/documents/{document_id}/pages/{page_no}/blocks';
};

export type DocumentsGetDocumentPageBlocksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsGetDocumentPageBlocksError = DocumentsGetDocumentPageBlocksErrors[keyof DocumentsGetDocumentPageBlocksErrors];

export type DocumentsGetDocumentPageBlocksResponses = {
    /**
     * Successful Response
     */
    200: PageBlocksResponse;
};

export type DocumentsGetDocumentPageBlocksResponse = DocumentsGetDocumentPageBlocksResponses[keyof DocumentsGetDocumentPageBlocksResponses];

export type DocumentsGetDocumentPageAnnotatedData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
        /**
         * Page No
         */
        page_no: number;
    };
    query?: never;
    url: '/documents/{document_id}/pages/{page_no}/annotated.png';
};

export type DocumentsGetDocumentPageAnnotatedErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsGetDocumentPageAnnotatedError = DocumentsGetDocumentPageAnnotatedErrors[keyof DocumentsGetDocumentPageAnnotatedErrors];

export type DocumentsGetDocumentPageAnnotatedResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DocumentsDeleteFieldReviewData = {
    body?: never;
    path: {
        /**
         * Document Id
         */
        document_id: string;
        /**
         * Review Id
         */
        review_id: number;
    };
    query?: never;
    url: '/documents/{document_id}/reviews/{review_id}';
};

export type DocumentsDeleteFieldReviewErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DocumentsDeleteFieldReviewError = DocumentsDeleteFieldReviewErrors[keyof DocumentsDeleteFieldReviewErrors];

export type DocumentsDeleteFieldReviewResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DocumentsDeleteFieldReviewResponse = DocumentsDeleteFieldReviewResponses[keyof DocumentsDeleteFieldReviewResponses];

export type RefineRefineExtractionData = {
    body?: never;
    path: {
        /**
         * Extraction Run Id
         */
        extraction_run_id: number;
    };
    query?: {
        /**
         * Page No
         * Page number to refine (1-indexed). Default 1.
         */
        page_no?: number;
    };
    url: '/refine/{extraction_run_id}';
};

export type RefineRefineExtractionErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefineRefineExtractionError = RefineRefineExtractionErrors[keyof RefineRefineExtractionErrors];

export type RefineRefineExtractionResponses = {
    /**
     * Successful Response
     */
    200: RefineResponse;
};

export type RefineRefineExtractionResponse = RefineRefineExtractionResponses[keyof RefineRefineExtractionResponses];

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};
