"""add_refinement_run_table

Revision ID: 9f4136a07caf
Revises: 3e2514bc236e
Create Date: 2026-05-07 03:58:17.229975

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9f4136a07caf"
down_revision: Union[str, None] = "3e2514bc236e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "refinement_run",
        sa.Column(
            "refinement_run_id",
            sa.BigInteger(),
            sa.Identity(always=True),
            nullable=False,
        ),
        sa.Column("extraction_run_id", sa.BigInteger(), nullable=False),
        sa.Column("vlm_model", sa.Text(), nullable=False),
        sa.Column("prompt_version", sa.Text(), nullable=False),
        sa.Column(
            "scaffold_in", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "scaffold_out", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("patches", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("arq_trace", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "token_usage", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "jsonb_typeof(patches) = 'array'", name="refinement_run_patches_is_array"
        ),
        sa.CheckConstraint(
            "jsonb_typeof(scaffold_in) = 'object'",
            name="refinement_run_scaffold_in_is_object",
        ),
        sa.CheckConstraint(
            "jsonb_typeof(scaffold_out) = 'object'",
            name="refinement_run_scaffold_out_is_object",
        ),
        sa.CheckConstraint("duration_ms >= 0", name="refinement_run_duration_nonneg"),
        sa.ForeignKeyConstraint(
            ["extraction_run_id"],
            ["extraction_run.extraction_run_id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("refinement_run_id"),
    )
    op.create_index(
        "ix_refinement_run_extraction_created",
        "refinement_run",
        ["extraction_run_id", "created_at"],
        unique=False,
    )
    op.create_index(
        "uq_refinement_run_one_current_per_extraction",
        "refinement_run",
        ["extraction_run_id"],
        unique=True,
        postgresql_where="is_current",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_refinement_run_one_current_per_extraction",
        table_name="refinement_run",
        postgresql_where="is_current",
    )
    op.drop_index("ix_refinement_run_extraction_created", table_name="refinement_run")
    op.drop_table("refinement_run")
    # ### end Alembic commands ###
